version: "3.8"

services:
  mock-data-loader:
    container_name: mock-data-loader
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "sleep 20;
      kafkacat -b kafka1:19092 -K: -t fhir.post-gateway-kdb -P -l /data/mock-data-kdb.ndjson;

      "
    volumes:
      - ./test-data/mock-data-kdb.ndjson:/data/mock-data-kdb.ndjson:ro
    depends_on:
      - kafka1

  zoo1:
    container_name: zoo1
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1

  akhq:
    container_name: akhq
    image: tchiotludo/akhq:0.20.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 8082:8080
    depends_on:
      - kafka1
  
  # https://github.com/bitnami/bitnami-docker-spark
  spark:
    container_name: spark
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8083:8080'
  spark-worker:
    container_name: spark-worker
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  bunsen:
    container_name: bunsen
    build:
      context: ./
      dockerfile: Dockerfile.bunsen 
    ports: 
      - 4040:4040
      - 8888:8888
    volumes:
      - ./volume:/home/jovyan/work
